### ISSUE TITLE
run the scraper again

### ISSUE THREAD

**Issue by tonyfast** [baronvonbadguy/genius-scraper#2]
before you do a big refactor can you toss up an updated `zip` file of the scraped data?

**Comment by baronvonbadguy** [comment]
Yezzir, currently I'm just getting it runnable, and I'll have it download all the lyrics of each artist on the wikipedia page from which I'm pulling names.  Then we'll have a much bigger dataset before I start refactoring.

**Comment by tonyfast** [comment]
Nice, let me know when its up!  Thanks dude.
